### ISSUE TITLE
this is virus  !!1!!11!

### ISSUE THREAD

**Issue by SupJko** [gamerbross/no-valkyrie-plugin-pak#1]
this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!this is virus  !!1!!11!

**Comment by gamerbross** [comment]
Ye ofc
