### ISSUE TITLE
Not working since fall guys update [Fixed]

### ISSUE THREAD

**Issue by osgamerxd** [gamerbross/no-valkyrie-plugin-pak#2]
![Screenshot 2024-08-15 152336](https://github.com/user-attachments/assets/348c2762-e6ba-4e0a-8ece-00da850771e6)

uefn unlocker works fine it just no-valkyrie-plugin-pakg

**Comment by osgamerxd** [comment]
sorry i just saw your twitter account and realize that you fix it

**Comment by SU-Daigoro** [comment]
Can you guide me there?
